name: Send Weather Mail

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master

jobs:
  build:
    name: Check Site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: 'Install NPM dependencies'
      run: 
        npm install axios moment gist-box
        
    - name: Run
      run: node index.js
      env:
        GIST_ID: '6445484d9c0dd5eca236b37413d022cc'
        TOKEN: ${{ secrets.token }}
